services:
  langflow:
    image: langflowai/langflow:latest
    container_name: langflow
    hostname: langflow
    restart: unless-stopped
    ports:
      - "7860:7860"
    volumes:
      - "./files:/app/files"

